/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGral_Celular;

import PROYECTO.delegate.SistemaDelegate;
import PROYECTO.dt.empleadoDT;
import VistasGral_Celular.Rcelular;
import javax.swing.JOptionPane;

/**
 *
 * @author jamon
 */
public class AltaEmpleado extends javax.swing.JInternalFrame {

    empleadoDT dto = new empleadoDT();
    SistemaDelegate fc = new SistemaDelegate();

    /**
     * Creates new form AltaEmpleado
     */
    public AltaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Rcelular validarDatosEMPLEADO = new Rcelular();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Sexo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_idEmpleado = new javax.swing.JTextField();
        txt_idTienda = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Cargo = new javax.swing.JTextField();
        txt_Celular = new javax.swing.JTextField();
        txt_e = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        btn_SALIR = new javax.swing.JButton();
        combo_Sexo = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel1.setText("Alta Empleado");

        jLabel2.setText("ID Empleado");

        jLabel3.setText("ID Tienda");

        jLabel4.setText("Nombre Empleado");

        jLabel5.setText("Cargo");

        jLabel6.setText("Celular");

        jLabel7.setText("e-mail");

        jLabel8.setText("Sexo");

        txt_idEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idEmpleadoActionPerformed(evt);
            }
        });
        txt_idEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idEmpleadoKeyTyped(evt);
            }
        });

        txt_idTienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idTiendaKeyTyped(evt);
            }
        });

        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });

        txt_Cargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CargoKeyTyped(evt);
            }
        });

        txt_Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CelularKeyTyped(evt);
            }
        });

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_SALIR.setText("Salir");
        btn_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SALIRActionPerformed(evt);
            }
        });

        combo_Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txt_idTienda)
                            .addComponent(txt_Nombre)
                            .addComponent(txt_Cargo)
                            .addComponent(txt_Celular)
                            .addComponent(txt_e)
                            .addComponent(combo_Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(combo_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btn_SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idEmpleadoActionPerformed

    private void btn_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SALIRActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_SALIRActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        // TODO add your handling code here:
        if(txt_idEmpleado.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el IdEmpleado","error",JOptionPane.ERROR_MESSAGE);
       }
        else if(txt_idTienda.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el IdTienda","error",JOptionPane.ERROR_MESSAGE);
       }
        else if(txt_Nombre.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el Nombre","error",JOptionPane.ERROR_MESSAGE);
       }
        else  if(txt_Cargo.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el Cargo","error",JOptionPane.ERROR_MESSAGE);
       }
        else  if(txt_Celular.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el Celular","error",JOptionPane.ERROR_MESSAGE);
       }
        else  if(txt_e.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingrese el Email","error",JOptionPane.ERROR_MESSAGE);
       }
        else  if(txt_Sexo.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el Sexo","error",JOptionPane.ERROR_MESSAGE);
       }
        try {
            dto.setIdnumEmpleado(Integer.parseInt(txt_idEmpleado.getText()));
            dto.setIdtienda(Integer.parseInt(txt_idTienda.getText()));
            dto.setNombre(txt_Nombre.getText());
            dto.setCargo(txt_Cargo.getText());
            dto.setCelular(Integer.parseInt(txt_Celular.getText()));
            dto.setEmail(txt_e.getText());
            dto.setSexo(String.valueOf(combo_Sexo.getSelectedItem()
                .toString().charAt(0)));
            
            fc.agregaEmpleado(dto);
            JOptionPane.showMessageDialog(this,"DATOS GUARDADOS CORRECTAMENTE");
            vaciar();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void txt_idEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idEmpleadoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_idEmpleadoKeyTyped

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Letras"); 
        }
    }//GEN-LAST:event_txt_NombreKeyTyped

    private void txt_idTiendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idTiendaKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_idTiendaKeyTyped

    private void txt_CargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CargoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Letras"); 
        }
    }//GEN-LAST:event_txt_CargoKeyTyped

    private void txt_CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CelularKeyTyped
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_CelularKeyTyped


    
    public void vaciar()
    {
        
        txt_idEmpleado.setText(null);
        txt_idTienda.setText(null);
        txt_Nombre.setText(null);
        txt_Cargo.setText(null);
        txt_Celular.setText(null);
        txt_e.setText(null);
        combo_Sexo.setSelectedItem(null);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_SALIR;
    private javax.swing.JComboBox<String> combo_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Cargo;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Sexo;
    private javax.swing.JTextField txt_e;
    private javax.swing.JTextField txt_idEmpleado;
    private javax.swing.JTextField txt_idTienda;
    // End of variables declaration//GEN-END:variables
}
