/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGral_Celular;

import PROYECTO.delegate.SistemaDelegate;
import PROYECTO.dt.notaDT;
import VistasGral_Celular.Rcelular;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jamon
 */
public class AltaNota extends javax.swing.JInternalFrame {

    notaDT dto = new notaDT();
    SistemaDelegate fc = new SistemaDelegate();


    /**
     * Creates new form AltaNota
     */
    public AltaNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Rcelular validarDatosNOTA = new Rcelular();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_IDnota = new javax.swing.JTextField();
        txt_IDcelular = new javax.swing.JTextField();
        txt_Detalle = new javax.swing.JTextField();
        txt_Cantidad = new javax.swing.JTextField();
        txt_Total = new javax.swing.JTextField();
        combo_Dia = new javax.swing.JComboBox<>();
        combo_Mes = new javax.swing.JComboBox<>();
        combo_Ano = new javax.swing.JComboBox<>();
        btn_Agregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Alta Nota");

        jLabel2.setText("ID Nota");

        jLabel3.setText("ID Celular");

        jLabel4.setText("Fecha de Pago");

        jLabel5.setText("Detalle de la venta");

        jLabel6.setText("Cantidad de productos");

        jLabel7.setText("Precio total: ");

        txt_IDnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDnotaActionPerformed(evt);
            }
        });
        txt_IDnota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IDnotaKeyTyped(evt);
            }
        });

        txt_IDcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IDcelularKeyTyped(evt);
            }
        });

        txt_Detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DetalleKeyTyped(evt);
            }
        });

        txt_Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CantidadActionPerformed(evt);
            }
        });
        txt_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CantidadKeyTyped(evt);
            }
        });

        txt_Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TotalKeyTyped(evt);
            }
        });

        combo_Dia.setModel(new javax.swing.DefaultComboBoxModel(fc.numeros(1,31)));
        combo_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_DiaActionPerformed(evt);
            }
        });

        combo_Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "noviembre", "Diciembre" }));

        combo_Ano.setModel(new javax.swing.DefaultComboBoxModel(fc.numeros(1940,2020)));

        btn_Agregar.setText("Guardar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_IDnota)
                            .addComponent(txt_IDcelular)
                            .addComponent(txt_Total)
                            .addComponent(txt_Detalle)
                            .addComponent(txt_Cantidad)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(combo_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(306, 306, 306))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_IDnota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_IDcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CantidadActionPerformed
        // TODO add r handling code here:
    }//GEN-LAST:event_txt_CantidadActionPerformed

    private void txt_IDnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDnotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDnotaActionPerformed

    private void combo_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_DiaActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
      if(txt_IDnota.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa la IDnota","error",JOptionPane.ERROR_MESSAGE);
       }
        else if(txt_IDcelular.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el IDcelular","error",JOptionPane.ERROR_MESSAGE);
       }
        else if(combo_Dia.toString().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa un Dia","error",JOptionPane.ERROR_MESSAGE);
       }
        else if(combo_Mes.toString().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingrese un Mes","error",JOptionPane.ERROR_MESSAGE);
       }
        else if(combo_Ano.toString().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingrese un Año","error",JOptionPane.ERROR_MESSAGE);
       }
      else if(txt_Detalle.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el Detalle","error",JOptionPane.ERROR_MESSAGE);
       }
        else  if(txt_Cantidad.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa la Cantidad","error",JOptionPane.ERROR_MESSAGE);
       }
        else  if(txt_Total.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(null,"ingresa el Total","error",JOptionPane.ERROR_MESSAGE);
       }
        try {
            dto.setIdnota(Integer.parseInt(txt_IDnota.getText()));
            dto.setIdcelular(Integer.parseInt(txt_IDcelular.getText()));            
              String dia = combo_Dia.getSelectedItem().toString();
              String mes = combo_Mes.getSelectedItem().toString();
              String año = combo_Ano.getSelectedItem().toString();
              SimpleDateFormat df = new SimpleDateFormat("dd-MMMMM-yyyyy");
              String fecha = dia + "-" +mes + "-" +año;
              long Fecha=df.parse(fecha).getTime();
              Date fech =new Date(Fecha);            
              dto.setFechapago(fech);            
            dto.setDetalleventa(txt_Detalle.getText());
            dto.setCantidadproductos(Integer.parseInt(txt_Cantidad.getText())); 
            dto.setPreciototal(Double.parseDouble(txt_Total.getText()));         
            fc.crearrNOTA(dto);
            JOptionPane.showMessageDialog(this,"DATOS GUARDADOS CORRECTAMENTE");
            vaciar();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_AgregarActionPerformed

    
     public void vaciar()
    {
        
        txt_IDnota.setText(null);
        txt_IDcelular.setText(null);
        combo_Dia.setSelectedItem(null);
        combo_Mes.setSelectedItem(null);
        combo_Ano.setSelectedItem(null);        
        txt_Detalle.setText(null);
        txt_Cantidad.setText(null);
        txt_Total.setText(null);
    }
     
     
     
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_IDnotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDnotaKeyTyped
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_IDnotaKeyTyped

    private void txt_DetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DetalleKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Letras"); 
        }
    }//GEN-LAST:event_txt_DetalleKeyTyped

    private void txt_IDcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDcelularKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_IDcelularKeyTyped

    private void txt_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CantidadKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_CantidadKeyTyped

    private void txt_TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TotalKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(rootPane, "Ingresa Solo Numeros"); 
        }
    }//GEN-LAST:event_txt_TotalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JComboBox<String> combo_Ano;
    private javax.swing.JComboBox<String> combo_Dia;
    private javax.swing.JComboBox<String> combo_Mes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Detalle;
    private javax.swing.JTextField txt_IDcelular;
    private javax.swing.JTextField txt_IDnota;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables
}
