/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGral_Celular;

import PROYECTO.delegate.SistemaDelegate;
import PROYECTO.dt.clienteDT;
import PROYECTO.dt.tiendaDT;
import java.sql.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author UAEM-ING26
 */
public class ListaGralTienda extends javax.swing.JInternalFrame {
    tiendaDT dt= new tiendaDT();
    SistemaDelegate fc= new SistemaDelegate();
    /**
     * Creates new form ListaGralTienda
     */
    public ListaGralTienda() {
        initComponents();
        Llenado();
    }
    
     public void Llenado(){
        String columnas[] ={"Clave","Nombre","Telefono","Pais","Direccion","Correo","Horario","Rfc","Actualizar","Eliminar"};
        List lista;
        int fila=-1;
        try {
            Object[][] data =new Object[fc.ListasTienda(dt).size()][11];
            lista = fc.ListasTienda(dt);
            Iterator it= lista.iterator();
            while (it.hasNext()) {
                dt =(tiendaDT) it.next();
                fila++;
                data[fila][0]= dt.getIdtienda();
                data[fila][1]= dt.getNombre();
                data[fila][2]= dt.getTelefono();
                data[fila][3]= dt.getPais();
                data[fila][4]= dt.getDireccion();
                data[fila][5]= dt.getCorreo();
                data[fila][6]= dt.getHorario();
                data[fila][7]= dt.getRfc();
                data[fila][8]= "Actualiza";
                data[fila][9]= "Eliminar";
                tabla.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
               
        }} catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Lista General");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        dt.setIdtienda(Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString()));
        dt.setNombre(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
        dt.setTelefono(Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 2).toString()));
        dt.setPais(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
        dt.setDireccion(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
        dt.setCorreo(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());
        dt.setHorario(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());
        dt.setRfc(tabla.getValueAt(tabla.getSelectedRow(), 7).toString());
       
        
        //Actualizar
        if (tabla.getSelectedColumn()==8) {
            if (JOptionPane.showConfirmDialog(this, "Deseas actualizar?","Actualizar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
                try {
                    fc.cambiaTienda(dt);
                } catch (Exception e) {
                }
                
            }
        }
        //Eliminar
        if (tabla.getSelectedColumn()==9) {
            if (JOptionPane.showConfirmDialog(this, "Deseas eliminar?","Eliminar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
                try {
                    fc.borraTienda(dt);
                    //Llenado();
                } catch (Exception e) {
                }
                
            }
        }
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
