/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGral_Celular;

import PROYECTO.delegate.SistemaDelegate;
import PROYECTO.dt.notaDT;
import java.sql.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jamon
 */
public class ListaGeneral_Nota extends javax.swing.JInternalFrame {

    notaDT dt= new notaDT();
    SistemaDelegate fc= new SistemaDelegate();
    /**
     * Creates new form ListaGeneral_Nota
     */
    public ListaGeneral_Nota() {
        initComponents();
        Llenado();
    }
    public void Llenado(){
        String columnas[] ={"ID Nota","ID Celular","Fecha del pago","Detalle de la venta","Cantidad de Productos","Precio Total","Actualiza","elimina"};
        List lista;
        int fila=-1;
        try {
            Object[][] data =new Object[fc.seleccionarrtodoNOTA(dt).size()][9];
            lista = fc.seleccionarrtodoNOTA(dt);
            Iterator it= lista.iterator();
            while (it.hasNext()) {
                dt =(notaDT) it.next();
                fila++;
                data[fila][0]= dt.getIdnota();
                data[fila][1]= dt.getIdcelular();
                data[fila][2]= dt.getFechapago();
                data[fila][3]= dt.getDetalleventa();
                data[fila][4]= dt.getCantidadproductos();
                data[fila][5]= dt.getPreciototal();
                data[fila][6]= "Actualiza";
                data[fila][7]= "Eliminar";
                Tablon.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
               
        }} catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablon = new javax.swing.JTable();
        btn_Salir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel1.setText("Lista General de las Notas ajio ajio");

        Tablon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablon);

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void TablonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablonMouseClicked
        // TODO add your handling code here:
        dt.setIdnota(Integer.parseInt(Tablon.getValueAt(Tablon.getSelectedRow(), 0).toString()));
        dt.setIdcelular(Integer.parseInt(Tablon.getValueAt(Tablon.getSelectedRow(), 1).toString()));
        dt.setFechapago(Date.valueOf(Tablon.getValueAt(Tablon.getSelectedRow(), 2).toString()));
        dt.setDetalleventa(Tablon.getValueAt(Tablon.getSelectedRow(), 3).toString());
        dt.setCantidadproductos(Integer.parseInt(Tablon.getValueAt(Tablon.getSelectedRow(), 4).toString()));
        dt.setPreciototal(Double.parseDouble(Tablon.getValueAt(Tablon.getSelectedRow(), 5).toString()));   
        
        //Actualizar
        if (Tablon.getSelectedColumn()==6) {
            if (JOptionPane.showConfirmDialog(this, "Deseas actualizar?","Actualizar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
                try {
                    fc.actualizarrNOTA(dt);
                } catch (Exception e) {
                }
                
            }
        }
        //Eliminar
        if (Tablon.getSelectedColumn()==7) {
            if (JOptionPane.showConfirmDialog(this, "Deseas eliminar?","Eliminar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
                try {
                    fc.eliminarrNOTA(dt);
                    //Llenado();
                } catch (Exception e) {
                }
                
            }
        }
    }//GEN-LAST:event_TablonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablon;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
