/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGral_Celular;

import PROYECTO.delegate.SistemaDelegate;
import PROYECTO.dt.celularDT;
import PROYECTO.facade.SistemaFacade;
import java.sql.Connection;
import java.sql.Date;
import java.sql.Time;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Chuy
 */
public class ListaGral_Celular extends javax.swing.JInternalFrame {
    
        celularDT dto = new celularDT();
        SistemaDelegate Dl = new SistemaDelegate();
        SistemaFacade f = new SistemaFacade();
    /**
     * Creates new form ListaGral_Celular
     */
    public ListaGral_Celular() {
        initComponents();
        llenado();
    }
    public void llenado(){
        String[] columnas = {"IdCelular","IdEmpleado","IdCliente","Nombre","Os","Marca","Memoria","Precio","Compañia","Color","Num.Camaras","Pulgadas","FechaV","Pixeles","Act","Eliminar"};
        List lista;
        
        int fila = -1;
        
        try{
            Object [][] data = new Object[Dl.seleccionarrtodoCELULAR(dto).size()][17];
            lista = Dl.seleccionarrtodoCELULAR(dto);
            Iterator it=lista.iterator();
            
            while(it.hasNext())
            {
                dto = (celularDT)it.next();
                fila++;
                data[fila][0]=dto.getIdcelular();
                data[fila][1]=dto.getIdnumEmpleado();
                data[fila][2]=dto.getIdcliente();
                data[fila][3]=dto.getNombre();
                data[fila][4]=dto.getSisoperativo();
                data[fila][5]=dto.getMarca();
                data[fila][6]=dto.getMemoria();
                data[fila][7]=dto.getPrecio();
                data[fila][8]=dto.getCompañia();
                data[fila][9]=dto.getColor();
                data[fila][10]=dto.getCantidadcamaras();
                data[fila][11]=dto.getPulgadas();
                data[fila][12]=dto.getFechaventa();
                data[fila][13]=dto.getPixeles();
                data[fila][14]= "Actualizar";
                data[fila][15]= "Eliminar";
                
                
            }
            tab.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
        }catch(Exception e){
            
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Lista General de Telefonos");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 610, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        dto.setIdcelular(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 0).toString()));
        dto.setIdnumEmpleado(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 1).toString()));
        dto.setIdcliente(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 2).toString()));
        dto.setNombre(tab.getValueAt(tab.getSelectedRow(), 3).toString());
        dto.setSisoperativo(tab.getValueAt(tab.getSelectedRow(), 4).toString());
        dto.setMarca(tab.getValueAt(tab.getSelectedRow(), 5).toString());
        dto.setMemoria(tab.getValueAt(tab.getSelectedRow(), 6).toString());
        dto.setPrecio(Double.parseDouble(tab.getValueAt(tab.getSelectedRow(), 7).toString()));
        dto.setCompañia(tab.getValueAt(tab.getSelectedRow(), 8).toString());
        dto.setColor(tab.getValueAt(tab.getSelectedRow(), 9).toString());
        dto.setCantidadcamaras(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 10).toString()));
        dto.setPulgadas(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 11).toString()));
        dto.setFechaventa(Date.valueOf(tab.getValueAt(tab.getSelectedRow(), 12).toString()));
        dto.setPixeles(tab.getValueAt(tab.getSelectedRow(), 13).toString());
        
        //Actualizar
        if(tab.getSelectedColumn()==14)
        {
            if(JOptionPane.showConfirmDialog(this, "Desea Actualizar","Actualiizar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try{
                    f.actualizarCELULAR(dto);
                }catch(Exception e){
                    
                }
            }
        }
        
        //Eliminar
        if(tab.getSelectedColumn()==15)
        {
            if(JOptionPane.showConfirmDialog(this, "Desea Eliminar","Eliminar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try{
                    Dl.eliminarrCELULAR(dto);
                    llenado();
                }catch(Exception e){
                    
                }
            }
        }
    }//GEN-LAST:event_tabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
